version: '3.8'

services:
  web:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - /var/www/heyvoca_back/prod:/app
    env_file:
      - .env.prod
    environment:
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
    restart: always