version: '3.8'

services:
  web:
    build: .
    ports:
      - "5002:5000"
    env_file:
      - .env.dev
    networks:
      - heyvoca_back_dev_network

networks:
  heyvoca_back_dev_network:
    name: heyvoca_back_dev_network
