version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - heyvoca_back_prod_network

networks:
  heyvoca_back_prod_network:
    name: heyvoca_back_prod_network
