name: Deploy HeyVoca Backend

on:
  push:
    branches:
      - dev       # Development 환경
      - staging   # Staging 환경
      - main      # Production 환경

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub에서 코드 가져오기
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Docker Hub 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Docker 이미지 빌드 및 푸시
    - name: Build and push Docker image
      run: |
        IMAGE_TAG=${{ github.ref_name }}
        docker build -t whrksp126/heyvoca_back:latest .
        docker build -t whrksp126/heyvoca_back:$IMAGE_TAG .
        docker push whrksp126/heyvoca_back:latest
        docker push whrksp126/heyvoca_back:$IMAGE_TAG

    # 4. SSH 키 설정
    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 5. 서버에 접속하여 컨테이너 재시작
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} -t << 'EOF'
        BRANCH_NAME="${{ github.ref_name }}"
        echo "Deploying for branch: $BRANCH_NAME"

        if [ "$BRANCH_NAME" == "main" ]; then
          sudo systemctl stop heyvoca_back
          sudo docker pull whrksp126/heyvoca_back:latest
          sudo systemctl start heyvoca_back
        elif [ "$BRANCH_NAME" == "staging" ]; then
          sudo systemctl stop heyvoca_back_stg
          sudo docker pull whrksp126/heyvoca_back:latest
          sudo systemctl start heyvoca_back_stg
        elif [ "$BRANCH_NAME" == "dev" ]; then
          sudo systemctl stop heyvoca_back_dev
          sudo docker pull whrksp126/heyvoca_back:latest
          sudo systemctl start heyvoca_back_dev
        fi
        EOF
